### ISSUE TITLE
Duplicate content roots detected

### ISSUE THREAD

**Issue by justicerling** [lucidsoftware/sbt-cross#15]
In the IDEA version 19.2.1 ,SBT version 1.3.X，when i use the sbt-cross 4.0 to configure cross compiling , i got the below notification from idea ：
Duplicate content roots detected: Path [C:/workspace/scala/data-platform/model] of module [model] was removed from modules [model]
And below is the main sbt configuration for  model :
`/** ***************************data-model module ****************************************************/
val modelDependencies = Seq(guava)
lazy val model = Project("model", file("model")).settings(commonSettings: _*)
        .settings(
            name := "model",
            libraryDependencies ++= modelDependencies,
        ).cross
lazy val model2_11 = model(scala2_11)
lazy val model2_12 = model(scala2_12)`
But in IDEA version 18.3  ,SBT version 1.3.X ,everything is going well

**Comment by tmccombs** [comment]
I think this might be the same as this IntelliJ bug: https://youtrack.jetbrains.com/issue/IDEA-210311

The way sbt-cross works is it creates separate sub-projects for each scala version, which all have the same content roots.

**Comment by justicerling** [comment]
This issue had been fixed in IDEA-2020.1.
